Create Mobile version
RHK-MICROVERSE/Conference pull request #5
Opened 2023-03-17 17:14 UTC by RHK-MICROVERSE

Mobile version has been created for the Online Conference project.

2023-03-17 20:02 UTC, divinecharlotte requested changes
Hi @RHK-MICROVERSE   ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100:
- No linters errors :heavy_check_mark:
- Descriptive commit messages :heavy_check_mark:
- clean code :heavy_check_mark:
- Descriptive PR :heavy_check_mark:


![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes :recycle:

- [ ] Project documentation
- kindly consider making your video brief so as you don't do beyond the maximum time given  and it will help you full-fill the below requirement 👇 
> The maximum length of the video is 5 minutes.
- kindly consider including a clear and objective description about the project kindly make sure  The topic and purpose of the project are made clear.

- [ ] Readme
- kindly consider deploying your project using Github pages this will help you hit this point in the requirement 👇 
> The student makes use of GitHub Pages to deploy the web pages.

and consider making sure that The project is deployed properly, all pages, links, and images work as expected. this will make your project give good user experience
- kindly consider adding the deployed link of your project cause currently the link is empty and this will improve the user experience where everyone visiting your project will have an easy way to access your project
 

- [ ] index.html
- kindly consider adding at least 1, but no more than 1, `h1` tag in each page.  and this will help you folow the HTML and CSS best practices
hint : you can do so by making `CREATIVE COMMONS
GLOBAL SUMMIT
2023` an H1 and remove the other ones  you can check more by checking on HTMLand CSS best practices

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!:clap::clap::clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 20:02 UTC, divinecharlotte commented on index.html
>      <nav class="top-navbar" >
- [ ] kindly consider displaying this `top-navbar` visible on desktop version on both pages this will make your design look more exact as the provided one check the images below for more clarification 
- your design 👇 
<img width="1293" alt="Screen Shot 2023-03-17 at 20 46 39" src="https://user-images.githubusercontent.com/60146030/225992292-f9b2c53c-46b0-4c01-ae65-7253837d73f3.png">

- provided design 👇 
<img width="855" alt="Screen Shot 2023-03-17 at 20 49 25" src="https://user-images.githubusercontent.com/60146030/225993047-07a183af-7ada-43c3-b3a9-9c9e7d1bd4ab.png">

2023-03-17 20:02 UTC, divinecharlotte commented on about.html
> +    </section>
- [ ] kindly consider adding this footer in the footer tag to make good use of Html semantic tags remember a footer is always a footer whether on mobile version or desktop
- [ ]  consider also giving it some padding so as to make a good duplicate of a provided design check below images for more clarification 
- your design 👇 
<img width="1317" alt="Screen Shot 2023-03-17 at 21 00 21" src="https://user-images.githubusercontent.com/60146030/225994832-8f7aa677-c5d5-4865-b5d1-208afddbd436.png">

- provided design 👇 
<img width="797" alt="Screen Shot 2023-03-17 at 21 03 10" src="https://user-images.githubusercontent.com/60146030/225995269-7f1f6d39-ac61-403c-a2f2-8f3d303e4363.png">

2023-03-17 20:02 UTC, divinecharlotte commented on about.html
>        </div>
- [ ] kindly consider adding a transparent background and and text centered over  these images to meet the provided design 
- your design 👇 
<img width="1440" alt="Screen Shot 2023-03-17 at 21 25 01" src="https://user-images.githubusercontent.com/60146030/226000851-39bef67c-6f9b-4221-8e67-bbf5f9030f89.png">

- provided design 👇 
<img width="629" alt="Screen Shot 2023-03-17 at 21 26 44" src="https://user-images.githubusercontent.com/60146030/226001101-a0bda367-8e1e-48f7-8864-5904b582e112.png">

2023-03-17 20:02 UTC, divinecharlotte commented on about.html
>              affiliate network in a different country every two years. This year, we hope to expand our invitation list including
- [ ] kindly consider giving the right color almost all your paragraphs to meet the designing and styling requirements as you can see you gave all your paragraphs a black color while it should have `#D3D3D3`

2023-03-18 10:30 UTC, joel-kalema approved these changes
Hi @RHK-MICROVERSE 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

- [ ] [OPTIONAL] Good job @RHK-MICROVERSE , but the previous forgot to tell you something most import ent. 
  -  Kindly make sure you implemented the functionality of the `More` button. As you can see in the [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), for the Desktop we are displaying all Speakers but for the Mobile, we are displaying only two items (speakers), and when we click on the `More` button, all speaker must be displayed 😃, and if we click on it again, only those two speakers must be displed 👍
  
![Capture099](https://user-images.githubusercontent.com/57408419/226099771-469e4722-2ed9-41d1-99c1-f1ac789219d0.PNG)

- [ ] [OPTIONAL] Kindly make sure you added some `padding` and the `background-color` to this  speaker section to follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015),
> | | Template | | Your project | |
> |-|---------|-|--------|-|
> | |![Capture01](https://user-images.githubusercontent.com/57408419/226099983-0a169664-c4b8-4c50-9a00-5346302258ff.PNG)| |![Capture](https://user-images.githubusercontent.com/57408419/226099955-be4e431f-6a15-4585-b7a2-a2e651fa3cf6.PNG)| |

 



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 10:34 UTC, RHK-MICROVERSE commented
Need to add a MORE button in the future for mobile view for the Featured Speaker Section.

2023-03-18 10:34 UTC, merged